use std::str::FromStr;
use crate::ast::*;

grammar;

pub File : File = {
    <m:Mod>
    <ts:Top*> => File {
        module: m,
        top_list: ts
    }
}

pub Mod : Mod = {
    "(" "module" <n:Id> ")" => Mod { name: n, export_list: vec![] }
}

pub Top : Top = {
    "(" "define" <n:Id> ")" => Top::DefineVar(n),
    "(" ":" <n:Id> ":"  ")" => Top::TypeDecl()
}

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();
Id: String = <s:r"[a-zA-Z_%!*+=?]+"> => s.into();
